#!/bin/bash

ctrc() {
	clear
	exit 0
}


trat ctrc INT

clear
while true; do

	echo ""
	echo "File Manager"
	echo "use help to help"
	echo ""
	echo -n "~$PWD $ "
	
	read command
	
	clear
	case $command in
		help)
		clear
		echo ""
       		echo "commands:"
        	echo "clear, see, edit, files, goto, delete"
        	echo ""
        	last="help"
		;;

		goto)
		clear
		echo ""
		echo "Where you want to go?"
		echo ""
		
		read goto
		cd $goto
		;;

		delete)
		clear
		echo ""
		echo "Delete wich file?"
		echo ""

		read del
		rm -r -f $del
		;;

		files)
		clear
		echo ""
		ls --color=auto
		echo ""
		;;

		exit)
		clear
		echo ""
		echo "exiting"
		echo ""
		exit 0
		;;
	
		see)
		echo ""
		echo "See wich file"
		echo ""
		
		read cat
		cat $cat
        echo ""
		;;

		edit)
		echo ""
		echo "Edit wich file?"
		echo ""
		
		read edt
		nano $edt
        	echo ""
        	;;

		clear)
		clear
		;;

        	*)
		echo ""
		echo "Command not found"
		echo ""
		;;
     esac

done
