#!/bin/bash
wmctrl -r :ACTIVE: -N "File manager"

usage="Commands:
executable Makes a file executable
execute    Executes an file
move       Move an directory or file 
clear      Clears commands output
see        Prints every line of a file
edit       Edit an file with vim
files      Prints files and directories in the current directory
goto       Navigate through the directories 
delete     Deletes files and directories
openimage  Opens an image"

# This is on a if & elif because i forgot case existed so yeah
while true; do
    if [[ $1 == -h ]]; then
        echo "Usage: $usage"
        exit 0
    elif [[ $1 == --help ]]; then
        echo "Usage: $usage"
        exit 0
    elif [[ $1 == -help ]]; then
        echo "Usage: $usage"
        exit 0
    elif [[ $1 == -usage ]]; then
        echo "Usage: $usage"
        exit 0
    elif [[ $1 == --usage ]]; then
        echo "Usage: $usage"
        exit 0
    elif [[ $1 == "" ]]; then
        break
    elif [[ $1 != -h && $1 != --help && $1 != -help && $1 != -usage && $1 != --usage ]]; then
        echo "Argument not found"
        echo "Use --help to help"
        exit 0
    fi
done

ctrc() {
	clear
	exit 0
}


trap ctrc INT

clear
while true; do

	echo ""
	echo "File Manager"
	echo "use help to help"
	echo ""
	echo -n "~$PWD $ "
	
	read command
	
	clear
	case $command in
		help)
		clear
		echo ""
       		echo "commands:"
        	echo "executable, execute, move, clear, see, edit, files, goto, delete"
        	echo "openimage"
            echo "For more help use Manager --help on the command line"
		echo ""
		;;

		goto)
		clear
		echo ""
		echo "Where you want to go?"
		echo ""
		
		read goto
		cd "$goto"
		;;

		delete)
		clear
		echo ""
		echo "Delete wich file?"
		echo ""

		read "del"
		rm -r -f "$del"
		;;

		files)
		clear
		echo ""
		ls --color=auto
		echo ""
		;;

		exit)
		clear
		echo ""
		echo "exiting"
		echo ""

		clear
		exit 0
		;;
	
		see)
		echo ""
		echo "See wich file"
		echo ""
		
		read "cat"
		cat "$cat"
        echo ""
		;;

		edit)
		echo ""
		echo "Edit wich file?"
		echo ""
		
		read "edt"
		nano "$edt"
        	echo ""
        	;;

		clear)
		clear
		;;

        	
		move)
		echo ""
		echo "Choose file to move"
		echo ""
		
		read "mv"
		clear

		echo ""
		echo "Choose location to move"
		echo ""
		
		read "loc"
		mv "$mv" "$loc"
		;;

		openimage)
		echo ""
		echo "Choose image to open"
		echo ""

		read "opn"
		clear

		if tiv "$opn"; then
			echo ""
		else
			echo ""
			echo "Error cant open '$opn' image, no image found"
		fi
		;;

        execute)
		echo ""
		echo "Choose file to execute"
		echo ""

		read "exc"
        clear        
            
		if ./"$exc"; then
            break
		else
			echo "Error cant find that file, have you marked it as an executable?"
		fi
		;;

        executable)
		echo ""
		echo "Choose file to make it executable"
		echo "Options: true/false"
		echo ""

		read "tof"

		clear

		if [[ $tof == true ]]; then
			echo ""
			echo "Choose file to make/remove it executable"
			echo ""

			read exec
			chmod +x $exec
		elif [[ $tof == false ]]; then
			clear
        else
			echo ""
			echo "Option not found"
			echo ""
        fi

        ;;

        *)
		echo ""
		echo "Command not found"
		echo ""
		;;        
        
     esac

done
