#!/bin/bash

ctrc() {
	clear
	exit 0
}


trat ctrc INT

clear
while true; do

	echo ""
	echo "File Manager"
	echo "use help to help"
	echo ""
	echo -n "~$PWD $ "
	
	read command
	
	clear
	case $command in
		help)
		clear
		echo ""
       		echo "commands:"
        	echo "executable, execute, move, clear, see, edit, files, goto, delete"
        	echo ""
        	last="help"
		;;

		goto)
		clear
		echo ""
		echo "Where you want to go?"
		echo ""
		
		read goto
		cd $goto
		;;

		delete)
		clear
		echo ""
		echo "Delete wich file?"
		echo ""

		read del
		rm -r -f $del
		;;

		files)
		clear
		echo ""
		ls --color=auto
		echo ""
		;;

		exit)
		clear
		echo ""
		echo "exiting"
		echo ""
		exit 0
		;;
	
		see)
		echo ""
		echo "See wich file"
		echo ""
		
		read cat
		cat $cat
        echo ""
		;;

		edit)
		echo ""
		echo "Edit wich file?"
		echo ""
		
		read edt
		nano $edt
        	echo ""
        	;;

		clear)
		clear
		;;

        	
		move)
		echo ""
		echo "Choose file to move without spaces"
		echo ""
		
		clear
		read mv

		echo ""
		echo "Choose location to move"
		echo ""
		
		read loc
		mv $mv $loc
		;;

        execute)
		echo ""
		echo "Choose file to execute"
		echo ""

		read exc
        clear        
            
		if ./$exc; then
            break
		else
			echo "Error cant find that file, have you marked it as an executable?"
		fi
		;;

        executable)
		echo ""
		echo "Choose file to make it executable"
		echo "Options: true/false"
		echo ""

		read tof

		clear

		if [[ $tof == true ]]; then
			echo ""
			echo "Choose file to make/remove it executable"
			echo ""

			read exec
			chmod +x $exec
		elif [[ $tof == false ]]; then
			clear
        else
			echo ""
			echo "Option not found"
			echo ""
        fi

        ;;

        *)
		echo ""
		echo "Command not found"
		echo ""
		;;        
        
     esac

done
